#!/bin/bash
#
# Runs a service container.
#

set -e

cd "$(dirname "$0")/../.."


docker container run \
  --rm \
  --interactive \
  --tty \
  --publish 4000:4000 \
  --name epoch-web \
  --env PHX_HOST=localhost \
  --env PORT=4000 \
  --env DATABASE_URL=ecto://postgres:postgres@host.docker.internal/epoch_dev \
  --env DATABASE_SSL=false \
  --env SECRET_KEY_BASE=XUHaTf95hc21ZGmnZZxestuSffWo2RRgTq+7l7d+1cygugxDsHeb3helkdU/oPnF \
  epoch-web bin/server
